### ISSUE TITLE
Uncaught TypeError : querySelectorAll

### ISSUE THREAD

**Issue by luweizheng** [Ovski4/jekyll-tabs#1]
Hi Baptiste,

I just install your tabs plugins. Now it can not display correct. 

![image](https://user-images.githubusercontent.com/57242864/102002046-bee16100-3d33-11eb-8e8b-9dd288a4f497.png)

And when I switch from on tab to another, I got the following error. Could you help me with it?

```
tabs.js:6 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at removeActiveClasses (tabs.js:6)
    at HTMLAnchorElement.<anonymous> (tabs.js:41)
```

**Comment by aleksandrenko** [comment]
Same here ...
Just not working.

**Comment by lgarbo** [comment]
If you copy  `jekyll-tabs.rb` and `template.erb` inside your `_plugins` directory it works

**Comment by Ovski4** [comment]
Sorry for the (very long) delay, I just noticed these open issues.

Feel free to let me know, and I'll re-open it if you need help. Please include steps, Jekyll versions and any useful information to help reproduce issues.
