### ISSUE TITLE
Page scrolls to top every time a tab is clicked

### ISSUE THREAD

**Issue by keriheuer** [Ovski4/jekyll-tabs#13]
I just installed this plugin and used the example Markdown/Liquid from the README. It's placed half-way down my page as I have other sections above the tabs. I'd like to be able to click on the different tabs without the page jumping to the very top every time I switch tabs. Is there a way to prevent this behavior?

**Comment by Ovski4** [comment]
Hello

I'm not sure how to reproduce this issue even if I have some ideas that could explain it. Could be the HTML markup, or maybe your website has other scripts conflicting with this plugin script?

Without more details I won't be able to help. Is your website live and public, and can I have access to it to investigate? Anything else you can provide that could be useful?

**Comment by Ovski4** [comment]
Closing as not reproductible

**Comment by q-wertz** [comment]
I'm having the same issue but only on the mobile version (Firefox).
Firefox on Desktop works fine.

Example: https://q-wertz.github.io/2024-04_navigation_auxiliary

**Comment by Ovski4** [comment]
What's your version of Android and what's you version of Firefox (mobile)? I browsed your website using Firefox Mobile and it looks good to me, when clicking on tabs.

I'm on Android 13 and here is the Firefox build info

![firefox-version](https://github.com/Ovski4/jekyll-tabs/assets/1218714/2fed08d5-9e44-4919-a006-494d60c1ab6b)

**Comment by q-wertz** [comment]
No idea what happened. Checked again today and it works now fine.

Android 13, Firefox 125.2.0, 
(same build as you have)

Last Firefox update was 3 days ago. Maybe [something there](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/125) fixed it
