### ISSUE TITLE
Tab content gets converted by Rouge highlighting 

### ISSUE THREAD

**Issue by jcapogna** [Ovski4/jekyll-tabs#2]
The second `ul` element in the template that contains the tab content is indented. This is not proper Kramdown, so it results in Jekyll not treating it as a continuation of the HTML block. As a result, the tab content ends up converted to code blocks by Rouge highlighting. 

This is fixed in @NejcZdovc's fork. 

https://github.com/NejcZdovc/jekyll-tabs

Please pull in his commit.

**Comment by Ovski4** [comment]
Sorry, I didn't realize people would find and use this gem. It was a one-time project for a very specific need I had, and I just noticed open issues.

Changes related to the template are on master and version 1.1.1.

> For anyone reading this comment in the future, I never wrote any ruby in my life except from the few hours I spent on this gem, so it might be a good idea not to put too much trust in it.
