### ISSUE TITLE
No license file in repository

### ISSUE THREAD

**Issue by RobertoJBeltran** [Ovski4/jekyll-tabs#3]
I see this project is released under MIT license on rubygems.org, but there is no license in the repository. It might be a good idea to add this so your intentions are clear and there is no confusion about the terms in dealing with your code. This is fairly easy to do and will help others feel confident in contributing to your project.

**Comment by Ovski4** [comment]
Thank you for opening this issue to tell me about this, that's very much appreciated.
I added a MIT License file.
