### ISSUE TITLE
Issue with github's jekyll-build-pages

### ISSUE THREAD

**Issue by pet-mit** [Ovski4/jekyll-tabs#4]
Hello 
Thank you so much for this plugin!

I implemented it using the guide you provided, everything seems to be working perfectly on my PC.
However, when deploying to github pages, I get this error:
"Liquid Exception: Liquid syntax error (line 22): Unknown tag 'tabs' in pages/...", on a .md page where I use tabs ("{% tabs aTab %}")
(Github builds Jekyll pages using actions here: https://github.com/actions/jekyll-build-pages)

Do you know if your plugin is supposed to work with github pages or if there could be some incompatibility?

Thank you for your help!
Peter

**Comment by pet-mit** [comment]
Here is a list of supported plugins:
https://pages.github.com/versions/

I have closed the issue

**Comment by Ovski4** [comment]
Yes you are right, GitHub Pages runs in safe mode and only allows a few plugins.

If it can help other people having the same issue, [here is a repo](https://github.com/jeffreytse/jekyll-deploy-action#-story) that can be used as a workaround. The other method would be to build locally.
