### ISSUE TITLE
Change all tabs when one is clicked

### ISSUE THREAD

**Issue by jmount1992** [Ovski4/jekyll-tabs#7]
Great plugin, and great instructions! It was easy to add! 

Unfortunately, I am not overly familiar with Javascript. I was wondering what JS would be required to make it so that when one tab is clicked then all tabs of the same type are clicked within other tab blocks. Does that make sense? For example, if I click Python, then all tab blocks that have a Python tab should move to show the Python code. I did try this myself but didn't have any luck.

Thanks for the plugin :)

**Comment by Ovski4** [comment]
I pushed some changes to the [tabs.js](https://github.com/Ovski4/jekyll-tabs/blob/master/docs/tabs.js) file that should allow you to do that. This is a very specific request so this behavior will be turned off by default.

You can:
- Update the content to the `tabs.js` with the latest version
- Follow instructions [here](https://github.com/Ovski4/jekyll-tabs#sync-tabs-with-similar-names)

Let me know if that works for you

**Comment by jmount1992** [comment]
Worked perfectly @Ovski4! It is a specific request but I think a great feature
